version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:615817570482:task-definition/TaskDefBlueGreen"
        LoadBalancerInfo:
          ContainerName: "nodeapp"
          ContainerPort: 8080
        PlatformVersion: "LATEST"